### ISSUE TITLE
Cannot edit data after specifying the rules

### ISSUE THREAD

**Issue by QuentinJanuel** [ProfessionalWiki/AutomatedValues#25]
Hi,

I installed this extension and tried to reproduce the example from the video.
I first created the following items and properties:
![data-before-rules](https://user-images.githubusercontent.com/29742359/217858825-3ca67f9b-5013-4a49-be94-5157575789fa.png)
![someone-data-before-rules](https://user-images.githubusercontent.com/29742359/217858864-12538d46-d384-4a3d-94e1-2ed412e4c2ea.png)
And I made the following rule:
![rules](https://user-images.githubusercontent.com/29742359/217858962-6bf102a1-2496-44ab-9c49-1a4991c04d44.png)
But then when I try to edit the Someone's statements to generate the automatic label, I get the following error:
![cant-edit](https://user-images.githubusercontent.com/29742359/217859336-5ff5729e-e227-4151-b1b0-9cf52a3052bf.png)

("P1/instance of" is of type "Item", and "P2/First name" and "P3/Last name" are of type "String")

**Comment by JeroenDeDauw** [comment]
Versions of PHP, MW, WB and the extension? Link to the wiki?

**Comment by QuentinJanuel** [comment]
Sorry, here are the versions:
PHP: 8.0.27 (apache2handler)
MW: 1.38.5
WB: 1.38

I just realised AutomatedValues is not compatible with WB 1.38 so I will try with an older version of WB

Also I have no idea how to get a detailed error message sorry

**Comment by QuentinJanuel** [comment]
It does work with WB1.37 and also with your compatibility fix, sorry again
