### ISSUE TITLE
Translation issue with message MediaWiki:Automated-values-config-invalid/en

### ISSUE THREAD

**Issue by verdy-p** [ProfessionalWiki/AutomatedValues#3]
URL: https://translatewiki.net/w/i.php?title=Special:Translate&showMessage=automated-values-config-invalid&group=mwgithub-automated-values&language=fr

Typo in English source. Change
> "[...] Your changes w**h**ere not saved."

to
> "[...] Your changes were not saved."

 (most probably, no need to revalidate existing translations?)

**Comment by JeroenDeDauw** [comment]
Thank you! Just fixed it in https://github.com/ProfessionalWiki/AutomatedValues/commit/93f22f4315b95bfa25db783dfecd82e78d1789fd
