### ISSUE TITLE
Product question: remove existing labels?

### ISSUE THREAD

**Issue by JeroenDeDauw** [ProfessionalWiki/AutomatedValues#4]
Premise: Existing labels are overridden by automatically generated ones.

```
	"buildLabel": {
		"en": {
			"P2": "$"
		}
	},
```

The above will replace the existing English label with the value of the first statement with property P2.

Question: But what should happen if there is no P2 statement? Should the English label be removed?

**Comment by mzeinstra** [comment]
Excellent question, I would say we need to force compliance so the English label should be removed.

However I can also imagine that we set this up as a variable in the config. e.g. "force": True
