### ISSUE TITLE
Contradiction for upper bound: Centralnotice-banner-history-logger-rate-help vs. Centralnotice-impression-events-sample-rate-field

### ISSUE THREAD

**Issue by verdy-p** [ProfessionalWiki/AutomatedValues#6]
There's an apparent contradiction in the new upper bound indicated between:

* Mediawiki:Centralnotice-banner-history-logger-rate-help/en:
> Probability that data will be sampled and sent back to the server. Decimal between 0 and 0.01.
* Mediawiki:Centralnotice-impression-events-sample-rate-field/en
> Impression events sample rate (should be between 0 and 0.1, inclusive)

Which one (0.01 or 0.1) is correct?

**Comment by kghbln** [comment]
This is the wrong issue tracker for the Centralnotice extension. Use [Phabricator](https://phabricator.wikimedia.org/maniphest/task/edit/form/1/?projects=i18n&title=MediaWiki%3ACentralnotice) instead. Thank you.

**Comment by verdy-p** [comment]
Sorry, this appeared in the same set of new translations.
