### ISSUE TITLE
Please give user MaartenZ rights to edit properties and config on demo wiki

### ISSUE THREAD

**Issue by mzeinstra** [ProfessionalWiki/AutomatedValues#7]
So I can make multiple examples / rules 

I want to add an additional rule to demo / test the selection of qualifiers and to show that multiple rule selectors are possible.

**Comment by JeroenDeDauw** [comment]
I have given you and `Digitaalwerktuig` the permission required to edit pages in the MediaWiki namespace.

As for editing properties, this should be possible by all registered users by default.

**Comment by mzeinstra** [comment]
Thanks,

I checked the additional functionality I wanted to test/demo and added steps to reproduce on the main wiki page.

Any feature that you @JeroenDeDauw, would like to highlight as well?
