### ISSUE TITLE
Unexpected behaviour – expected taking preferred rank over normal rank

### ISSUE THREAD

**Issue by mzeinstra** [ProfessionalWiki/AutomatedValues#8]
Not sure if this is a feature or a bug :)

When adding multiple last names I expected that the extension would take the first 'preferred rank' instead is taking the first entered statement.

<img width="934" alt="Screenshot 2022-03-28 at 13 49 38" src="https://user-images.githubusercontent.com/5627431/160392287-f21ac157-c679-4e7d-a8f7-1b7ccb4b2af3.png">

I expected this case to resolve the Label to "M wrong use of last name".

**Comment by JeroenDeDauw** [comment]
Should be fixed now.

Apparently I got confused when I wrote the docs. I never implemented this for building values. Only for finding matching entities via entity criteria.

**Comment by mzeinstra** [comment]
Is this deployed on the demo wiki?

If so, not sure it is fixed (or if not part of spec). In the attached screenshot I expected the label to be 'Pjotr Hein' instead of 'Piet Hein', since Piet is the deprecated rank and Pjotr is the preferred rank.

<img width="927" alt="Screenshot 2022-03-28 at 15 12 03" src="https://user-images.githubusercontent.com/5627431/160405167-b63e3fe0-82b4-4f56-a29d-79d1de6ceb21.png">

**Comment by JeroenDeDauw** [comment]
Oh sorry, not deployed yet :)

**Comment by JeroenDeDauw** [comment]
Should now be deployed on the demo wiki

**Comment by mzeinstra** [comment]
Not sure if this works as expected.

Do both ranks of First Name and Last Name need to be in sync? In the screenshot below I expect Pjotr Hein, not Pjotr. Also the aliases appear to be missing but present in Q4


<img width="943" alt="Screenshot 2022-03-28 at 15 51 25" src="https://user-images.githubusercontent.com/5627431/160412810-c37749d3-dc9d-4e30-bc3c-8cf45287f8ff.png">

**Comment by JeroenDeDauw** [comment]
I implemented the wrong behavior. The statements where getting filtered on the item level. So as soon as there was on preferred one, all normal ones would be ignored, even if there are no preferred ones for the same property.

Fixed now by filtering on statement group level. Deployment started, will be live in ~5 min.

**Comment by mzeinstra** [comment]
Verified that this now works as expected.
